spring:
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
  jpa:
    hibernate:
      ddl-auto: 'create-drop'
  h2:
    console:
      enabled: true

logging:
  level:
    root: INFO
    com.example.demo.service.StudentService: DEBUG